spring:
  h2:
    console:
      path: /h2-console
      enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/springblog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true


  data:
    redis:
      port: 6379
      host: localhost

logging:
  level:
    org.springframework.cache: trace